# Generated by Django 4.1.4 on 2022-12-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_email_verified_user_multifactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='backend',
        ),
    ]
