# Generated by Django 4.1.4 on 2023-02-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_user_backend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='multifactor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plugin_code',
        ),
        migrations.AddField(
            model_name='user',
            name='screen_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
