# Generated by Django 4.1.4 on 2023-02-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_remove_user_email_verified_remove_user_multifactor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
