# Generated by Django 4.1.4 on 2023-02-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_user_org_user_pending_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
