# Generated by Django 4.1.4 on 2023-03-07 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_user_is_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('key', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='API Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
