# Generated by Django 4.1.4 on 2023-03-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='last_four',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Last 4 of API Key'),
        ),
    ]
