# Generated by Django 4.1.4 on 2023-03-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_user_api_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
