# Generated by Django 4.1.4 on 2022-12-08 16:27

import cvdp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(blank=True, max_length=250, null=True)),
                ('preferred_username', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('logocolor', models.CharField(default=cvdp.models.random_logo_color, max_length=10)),
                ('pending', models.BooleanField(default=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('settings_pickled', models.TextField(blank=True, help_text='This is a base64-encoded representation of a pickled Python dictionary.Do not change this field via the admin.', null=True, verbose_name='Settings Dictionary')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
