# Generated by Django 4.1.4 on 2022-12-14 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0002_case_thread_userthread_thread_users_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread',
            new_name='MessageThread',
        ),
    ]
