# Generated by Django 4.1.4 on 2022-12-14 15:52

import cvdp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cvdp', '0003_rename_thread_messagethread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=cvdp.models.user_logo_path),
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor_type', models.CharField(choices=[('Vendor', 'Vendor'), ('Coordinator', 'Coordinator')], default='Vendor', max_length=50)),
                ('logo', models.FileField(blank=True, null=True, upload_to=cvdp.models.group_directory_path)),
                ('icon_color', models.CharField(default=cvdp.models.random_logo_color, max_length=10)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
