# Generated by Django 4.1.4 on 2022-12-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0007_contactassociation_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='summary',
            field=models.TextField(blank=True, help_text='A brief summary of the case', null=True),
        ),
    ]
