# Generated by Django 4.1.4 on 2022-12-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0008_alter_case_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_id',
            field=models.CharField(default=389284, max_length=20),
            preserve_default=False,
        ),
    ]
