# Generated by Django 4.1.4 on 2022-12-20 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cvdp', '0010_attachment_messageattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
                ('case', models.ForeignKey(help_text='The case this thread belongs to', on_delete=django.db.models.deletion.CASCADE, to='cvdp.case')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that started this thread', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pinned', models.BooleanField(default=False, help_text='A pinned post is pinned to the top of the page.')),
                ('deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, help_text='The writer of this post.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='attachment',
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(editable=False, verbose_name='revision number')),
                ('user_message', models.TextField(blank=True)),
                ('automatic_log', models.TextField(blank=True, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('locked', models.BooleanField(default=False, verbose_name='locked')),
                ('content', models.TextField(blank=True, verbose_name='vulnote contents')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.post', verbose_name='Post')),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.postrevision')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('created',),
                'get_latest_by': 'revision_number',
                'unique_together': {('post', 'revision_number')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='current_revision',
            field=models.OneToOneField(blank=True, help_text='The revision displayed for this post.  If you need to rollback, change value of this field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_set', to='cvdp.postrevision'),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group of the user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(help_text='The case this post belongs to', on_delete=django.db.models.deletion.CASCADE, to='cvdp.casethread'),
        ),
    ]
