# Generated by Django 4.1.4 on 2023-01-05 20:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0013_caseviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrevision',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='postrevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='post_gin'),
        ),
    ]
