# Generated by Django 4.1.4 on 2023-01-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0014_postrevision_search_vector_postrevision_post_gin'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            
            CREATE TRIGGER post_update_trigger
            BEFORE INSERT OR UPDATE of content
            ON cvdp_postrevision
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'pg_catalog.english', content);
            
            UPDATE cvdp_postrevision SET search_vector = NULL;
            ''',

            reverse_sql= '''
            DROP TRIGGER IF EXISTS post_update_trigger
            ON cvdp_postrevision;
           ''',
        ),

    ]
