# Generated by Django 4.1.4 on 2023-01-09 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0015_auto_20230105_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('seen', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('owner', 'owner'), ('reporter', 'reporter'), ('vendor', 'vendor'), ('participant', 'participant'), ('observer', 'observer')], default='vendor', max_length=30)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.case')),
                ('contact', models.ForeignKey(blank=True, help_text='A participant in the case (contact may not belong to a group)', null=True, on_delete=django.db.models.deletion.CASCADE, to='cvdp.contact')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(blank=True, help_text='The user that added the group/contact.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseThreadParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(help_text='The participant', on_delete=django.db.models.deletion.CASCADE, to='cvdp.caseparticipant')),
                ('thread', models.ForeignKey(help_text='The case thread', on_delete=django.db.models.deletion.CASCADE, to='cvdp.casethread')),
            ],
        ),
    ]
