# Generated by Django 4.1.4 on 2023-01-09 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0017_alter_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='casethreadparticipant',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casethreadparticipant',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='The user that added this user to this thread', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
