# Generated by Django 4.1.4 on 2023-01-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0018_casethreadparticipant_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casethread',
            name='official',
            field=models.BooleanField(default=True, help_text='The official case thread. Everyone participates.'),
        ),
    ]
