# Generated by Django 4.1.4 on 2023-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0019_casethread_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casethread',
            name='official',
            field=models.BooleanField(default=False, help_text='The official case thread. Everyone participates.'),
        ),
    ]
