# Generated by Django 4.1.4 on 2023-01-11 01:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0020_alter_casethread_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
