# Generated by Django 4.1.4 on 2023-01-18 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.forms.fields
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0023_auto_20230111_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.IntegerField(choices=[(0, django.forms.fields.CharField), (1, django.forms.widgets.Textarea), (2, django.forms.fields.IntegerField), (3, django.forms.fields.MultipleChoiceField), (4, django.forms.fields.BooleanField), (5, django.forms.fields.ChoiceField), (6, django.forms.fields.EmailField), (7, django.forms.fields.DateField)])),
                ('question', models.TextField()),
                ('question_choices', models.TextField(blank=True, help_text='Line separated options where applicable', null=True, verbose_name='Choices')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order of question')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, help_text='Description of report', null=True)),
                ('intro', models.TextField(blank=True, help_text='Provide users with info about what they can expect when filling out this form.', verbose_name='Form Intro')),
                ('send_ack_email', models.BooleanField(default=True, help_text='If checked, send an acknowledgement email')),
                ('email_from', models.EmailField(blank=True, help_text='The address the email will be sent from', max_length=254, verbose_name='Email from address')),
                ('email_subject', models.CharField(blank=True, max_length=200, verbose_name='Email Subject')),
                ('email_answers', models.BooleanField(default=True, help_text='If checked, include report answers in the ack email', verbose_name='Include Responses in Email')),
                ('email_message', models.TextField(blank=True, verbose_name='Message')),
                ('login_required', models.BooleanField(default=False, help_text='If checked, only logged in users can view/submit form.')),
                ('allow_file_upload', models.BooleanField(default=False, help_text='Allow user to upload file.')),
            ],
            options={
                'verbose_name': 'Reporting Form',
                'verbose_name_plural': 'Reporting Forms',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cvdp.formquestion')),
            ],
            options={
                'verbose_name': 'Form question entry',
                'verbose_name_plural': 'Form question entries',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formquestion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.reportingform'),
        ),
        migrations.CreateModel(
            name='FormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cvdp.reportingform')),
            ],
            options={
                'verbose_name': 'Form entry',
                'verbose_name_plural': 'Form entries',
                'abstract': False,
            },
        ),
    ]
