# Generated by Django 4.1.4 on 2023-01-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0024_formquestion_reportingform_questionentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cvdp.reportingform'),
        ),
    ]
