# Generated by Django 4.1.4 on 2023-01-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0025_alter_formquestion_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'Single Line Text'), (1, 'Multi Line Text'), (2, 'Number'), (3, 'Checkbox Multiple'), (4, 'Checkbox'), (5, 'Select'), (6, 'Email'), (7, 'Date'), (8, 'Radio Buttons')]),
        ),
    ]
