# Generated by Django 4.1.4 on 2023-01-19 19:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0026_alter_formquestion_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.JSONField(help_text='JSON dictionary with report')),
                ('received', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, help_text='URL, automated source, email', max_length=300, null=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.formentry')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.casereport'),
        ),
    ]
