# Generated by Django 4.1.4 on 2023-01-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0027_casereport_case_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Keep answers private'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
