# Generated by Django 4.1.4 on 2023-01-20 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0028_formquestion_private_alter_case_case_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=150, verbose_name='Template Name')),
                ('template_type', models.IntegerField(choices=[(0, 'Case'), (1, 'User'), (2, 'Report'), (3, 'Message')])),
                ('subject', models.CharField(help_text='If related to a case, this will be prefixed with the case ID and/or any user supplied identifier', max_length=150, verbose_name='Subject')),
                ('plain_text', models.TextField(help_text='The contents of the email in plain text. If related to a case, generic case information will be available through the context.', verbose_name='Plain Text')),
                ('html', models.TextField(help_text='The HTML version of the email, with the same context available in the plain text version.', verbose_name='HTML')),
                ('locale', models.CharField(blank=True, help_text='Locale of this template.', max_length=10, null=True, verbose_name='Locale')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user that added this template, or if null most likely it was system generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'e-mail template',
                'verbose_name_plural': 'e-mail templates',
                'ordering': ('template_name', 'locale'),
            },
        ),
    ]
