# Generated by Django 4.1.4 on 2023-01-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0029_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Inactive')], default=0, verbose_name='Status'),
        ),
    ]
