# Generated by Django 4.1.4 on 2023-01-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cvdp', '0030_alter_case_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('component_type', models.CharField(choices=[('Application', 'Application'), ('Container', 'Container'), ('Device', 'Device'), ('Library', 'Library'), ('File', 'File'), ('Firmware', 'Firmware'), ('Framework', 'Framework'), ('Operating System', 'Operating System'), ('Service', 'Service'), ('Other', 'Other')], max_length=50)),
                ('version', models.CharField(max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.TextField(blank=True, help_text='Download Location', null=True)),
                ('homepage', models.CharField(blank=True, max_length=500, null=True)),
                ('checksum', models.CharField(blank=True, max_length=500, null=True)),
                ('external_ids', models.JSONField(blank=True, help_text='Other unique identifiers, like CPE, SWID, or PURL in a JSON dict', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ('Component',),
                'verbose_name_plural': 'Components',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.component')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='cvdp.component')),
                ('dependencies', models.ManyToManyField(through='cvdp.ComponentRelationship', to='cvdp.component')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='componentrelationship',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.product'),
        ),
    ]
