# Generated by Django 4.1.4 on 2023-02-08 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0035_remove_userprofile_org_remove_userprofile_pending_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWEDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cwe', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('modified',)},
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='date_public',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='problem_types',
            field=models.JSONField(blank=True, null=True, verbose_name='Problem Type'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='references',
            field=models.JSONField(blank=True, null=True, verbose_name='References'),
        ),
        migrations.CreateModel(
            name='VulnerabilityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(help_text='The tag', max_length=50)),
                ('user', models.ForeignKey(blank=True, help_text='User that created this tag.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.vulnerability', verbose_name='Vulnerability')),
            ],
        ),
    ]
