# Generated by Django 4.1.4 on 2023-02-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0036_cwedescriptions_alter_case_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEServicesAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(help_text='Organization registered with CVE Services', max_length=200, verbose_name='Organization')),
                ('api_key', models.CharField(help_text='API Key', max_length=100, verbose_name='API Key')),
                ('email', models.EmailField(help_text='Email associated with the account', max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
