# Generated by Django 4.1.4 on 2023-02-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0037_cveservicesaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Estimated Public Date', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='public_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
