# Generated by Django 4.1.4 on 2023-02-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0039_assignmentrole_userassignmentweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='casethread',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
