# Generated by Django 4.1.4 on 2023-02-13 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0040_casethread_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(choices=[('Application', 'Application'), ('Container', 'Container'), ('Device', 'Device'), ('Library', 'Library'), ('File', 'File'), ('Firmware', 'Firmware'), ('Framework', 'Framework'), ('Operating System', 'Operating System'), ('Service', 'Service'), ('Other', 'Other')], default='Application', max_length=50),
        ),
        migrations.AlterField(
            model_name='userassignmentweight',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='cvdp.assignmentrole'),
        ),
        migrations.CreateModel(
            name='StatusRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(editable=False, verbose_name='revision number')),
                ('user_message', models.TextField(blank=True)),
                ('automatic_log', models.TextField(blank=True, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('locked', models.BooleanField(default=False, verbose_name='locked')),
                ('status', models.IntegerField(choices=[(0, 'Not Affected'), (1, 'Affected'), (2, 'Fixed'), (3, 'Under Investigation')])),
                ('version_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Affected Version End Range')),
                ('version_affected', models.CharField(blank=True, choices=[('None', None), ('<', '< (affects X versions prior to n)'), ('<=', '<= (affects X versions up to n)'), ('=', '= (affects n)'), ('>', '> (affects X versions above n)'), ('>=', '>= (affects X versions n and above)')], max_length=10, null=True, verbose_name='Version Affected')),
                ('version_value', models.CharField(max_length=100, verbose_name='Affected Version Value or Start Range')),
                ('statement', models.TextField(blank=True, null=True)),
                ('component_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.componentstatus', verbose_name='Component Status')),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.statusrevision')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('created',),
                'get_latest_by': 'revision_number',
                'unique_together': {('component_status', 'revision_number')},
            },
        ),
        migrations.AddField(
            model_name='componentstatus',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.component'),
        ),
        migrations.AddField(
            model_name='componentstatus',
            name='current_revision',
            field=models.OneToOneField(blank=True, help_text='The current status revision', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_set', to='cvdp.statusrevision'),
        ),
        migrations.AddField(
            model_name='componentstatus',
            name='vul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.vulnerability'),
        ),
    ]
