# Generated by Django 4.1.4 on 2023-02-15 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0042_action_alter_statusrevision_version_affected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cveservicesaccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cveservicesaccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='cveservicesaccount',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cveservicesaccount',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group that can use to make CVE reservations. Otherwise user only.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AddField(
            model_name='cveservicesaccount',
            name='server_type',
            field=models.CharField(choices=[('prod', 'Production'), ('test', 'Test'), ('dev', 'Development')], default='prod', max_length=10),
        ),
        migrations.AddField(
            model_name='cveservicesaccount',
            name='user_added',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cveservicesaccount',
            name='org_name',
            field=models.CharField(help_text='Organization registered with CVE Services (CNA Short Name)', max_length=200, verbose_name='Organization'),
        ),
        migrations.CreateModel(
            name='CVEReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50)),
                ('time_reserved', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, help_text='Account used to create reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.cveservicesaccount')),
                ('user_reserved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vul', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.vulnerability')),
            ],
        ),
    ]
