# Generated by Django 4.1.4 on 2023-02-18 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0043_remove_cveservicesaccount_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulCVSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AV', models.CharField(max_length=2, verbose_name='Attack Vector')),
                ('AC', models.CharField(max_length=2, verbose_name='Attack Complexity')),
                ('PR', models.CharField(max_length=2, verbose_name='Privileges Required')),
                ('UI', models.CharField(max_length=2, verbose_name='User Interaction')),
                ('S', models.CharField(max_length=2, verbose_name='Scope')),
                ('C', models.CharField(max_length=2, verbose_name='Confidentiality')),
                ('I', models.CharField(max_length=2, verbose_name='Integrity')),
                ('A', models.CharField(max_length=2, verbose_name='Availability')),
                ('E', models.CharField(default='X', max_length=2, verbose_name='Exploit Code Maturity')),
                ('RL', models.CharField(default='X', max_length=2, verbose_name='Remediation Level')),
                ('RC', models.CharField(default='X', max_length=2, verbose_name='Report Confidence')),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified Date')),
                ('vector', models.CharField(blank=True, max_length=100, null=True, verbose_name='CVSS Vector String')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='CVSS Base Score')),
                ('severity', models.CharField(blank=True, max_length=20, null=True, verbose_name='CVSS Severity')),
                ('scored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cvdp.vulnerability')),
            ],
        ),
    ]
