# Generated by Django 4.1.4 on 2023-02-21 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0044_vulcvss'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulSSVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_tree', models.JSONField(verbose_name='SSVC Decisions')),
                ('tree_type', models.CharField(max_length=100)),
                ('final_decision', models.CharField(max_length=50)),
                ('vector', models.CharField(max_length=100)),
                ('last_edit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cvdp.vulnerability')),
            ],
        ),
    ]
