# Generated by Django 4.1.4 on 2023-02-23 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0045_vulssvc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(editable=False, verbose_name='revision number')),
                ('user_message', models.TextField(blank=True)),
                ('automatic_log', models.TextField(blank=True, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('locked', models.BooleanField(default=False, verbose_name='locked')),
                ('content', models.TextField(blank=True, verbose_name='advisory contents')),
                ('title', models.CharField(help_text='Each revision contains a title field that must be filled out, even if the title has not changed', max_length=512, verbose_name='advisory title')),
                ('references', models.JSONField(blank=True, verbose_name='references')),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('date_shared', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='postrevision',
            name='content',
            field=models.TextField(blank=True, verbose_name='post contents'),
        ),
        migrations.CreateModel(
            name='CaseAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(help_text='Advisory for the case.', on_delete=django.db.models.deletion.CASCADE, to='cvdp.case')),
                ('current_revision', models.OneToOneField(blank=True, help_text='The current revision. If you need to rollback, change value of this field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_set', to='cvdp.advisoryrevision')),
            ],
        ),
        migrations.AddField(
            model_name='advisoryrevision',
            name='advisory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.caseadvisory', verbose_name='advisory'),
        ),
        migrations.AddField(
            model_name='advisoryrevision',
            name='previous_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.advisoryrevision'),
        ),
        migrations.AddField(
            model_name='advisoryrevision',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
