# Generated by Django 4.1.4 on 2023-02-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0046_advisoryrevision_alter_postrevision_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisoryrevision',
            options={'get_latest_by': 'revision_number', 'ordering': ('created',)},
        ),
        migrations.AlterUniqueTogether(
            name='advisoryrevision',
            unique_together={('advisory', 'revision_number')},
        ),
    ]
