# Generated by Django 4.1.4 on 2023-02-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0048_alter_advisoryrevision_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseadvisory',
            name='date_last_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseadvisory',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
