# Generated by Django 4.1.4 on 2023-02-24 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0049_caseadvisory_date_last_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
