# Generated by Django 4.1.4 on 2023-02-25 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0050_component_added_by_component_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_username',
        ),
    ]
