# Generated by Django 4.1.4 on 2023-03-03 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0052_contactassociation_group_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_thread', to='cvdp.post')),
                ('replies', models.ManyToManyField(through='cvdp.PostReply', to='cvdp.post')),
            ],
        ),
        migrations.AddField(
            model_name='postreply',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.postthread'),
        ),
    ]
