# Generated by Django 4.1.4 on 2023-03-03 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0053_postreply_postthread_postreply_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportingform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportingform',
            name='email_message',
            field=models.TextField(blank=True, verbose_name='Email Message Content'),
        ),
    ]
