# Generated by Django 4.1.4 on 2023-03-07 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0054_reportingform_created_reportingform_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Date this case was most recently changed.', verbose_name='Modified'),
            preserve_default=False,
        ),
    ]
