# Generated by Django 4.1.4 on 2023-03-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0055_alter_case_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('-modified',)},
        ),
    ]
