# Generated by Django 4.1.4 on 2023-03-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0058_caseartifact_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='mailing_address',
            field=models.TextField(blank=True, help_text='Organization mailing address/location', null=True),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Team or contact email address for organization', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='support_phone',
            field=models.CharField(blank=True, help_text='Team or contact phone number for organization', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Organization/support website', null=True),
        ),
    ]
