# Generated by Django 4.1.4 on 2023-03-21 14:21

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0059_groupprofile_mailing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='case',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='case_gin'),
        ),
    ]
