# Generated by Django 4.1.4 on 2023-03-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0061_auto_20230321_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
