# Generated by Django 4.1.4 on 2023-03-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0063_alter_component_options_component_modified_and_more'),
    ]

    operations = [

        migrations.RunSQL(
            sql='''

            CREATE TRIGGER component_update_trigger
            BEFORE INSERT OR UPDATE of name, component_type, version, supplier, source, homepage, checksum, comment
            ON cvdp_component
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'pg_catalog.english', name, component_type, version, supplier, source, homepage, checksum, comment);

            UPDATE cvdp_component SET search_vector = NULL;
            ''',

            reverse_sql= '''
            DROP TRIGGER IF EXISTS component_update_trigger
            ON cvdp_component;
           ''',
        ),

        
    ]
