# Generated by Django 4.1.4 on 2023-03-21 18:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0064_auto_20230321_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={},
        ),
        migrations.AddField(
            model_name='advisoryrevision',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='advisoryrevision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='advisory_gin'),
        ),
    ]
