# Generated by Django 4.1.7 on 2023-03-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0066_auto_20230321_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(blank=True, help_text='If present, this will be used for a header in the HTML email. Not used for plain text emails.', max_length=250, null=True, verbose_name='HTML Email Title'),
        ),
    ]
