# Generated by Django 4.1.7 on 2023-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0067_emailtemplate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.IntegerField(choices=[(0, 'Case'), (1, 'User'), (2, 'Report'), (3, 'Message'), (4, 'Post')]),
        ),
    ]
