# Generated by Django 4.1.7 on 2023-03-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0068_alter_emailtemplate_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseparticipant',
            name='notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
