# Generated by Django 4.1.7 on 2023-04-18 18:18

import advise.storage_backends
import cvdp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0069_caseparticipant_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=1000, storage=advise.storage_backends.AttachmentFileStorage(), upload_to=cvdp.models.get_uuid_filename, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='product',
            name='component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='cvdp.component'),
        ),
    ]
