# Generated by Django 4.1.7 on 2023-04-24 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0070_alter_attachment_file_alter_product_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethread',
            name='users',
            field=models.ManyToManyField(blank=True, through='cvdp.UserThread', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread', models.BooleanField()),
                ('deleted', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.messagethread')),
            ],
        ),
        migrations.AddField(
            model_name='messagethread',
            name='groups',
            field=models.ManyToManyField(blank=True, through='cvdp.GroupThread', to='auth.group'),
        ),
    ]
