# Generated by Django 4.1.7 on 2023-04-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0072_globalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cvdp.action')),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvdp.caseartifact')),
                ('case', models.ForeignKey(help_text='Case', on_delete=django.db.models.deletion.CASCADE, to='cvdp.case')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.caseparticipant')),
                ('vulnerability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvdp.vulnerability')),
            ],
            bases=('cvdp.action',),
        ),
        migrations.AlterField(
            model_name='statusrevision',
            name='version_affected',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('<', '<'), ('<=', '<='), ('=', '='), ('>', '>'), ('>=', '>=')], max_length=10, null=True, verbose_name='Version Affected'),
        ),
        migrations.CreateModel(
            name='CaseChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Field')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='New Value')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.caseaction')),
            ],
        ),
    ]
