# Generated by Django 4.1.7 on 2023-04-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0073_caseaction_alter_statusrevision_version_affected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseaction',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.caseartifact'),
        ),
        migrations.AlterField(
            model_name='caseaction',
            name='vulnerability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.vulnerability'),
        ),
    ]
