# Generated by Django 4.1.7 on 2023-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0074_alter_caseaction_artifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseaction',
            name='action_type',
            field=models.IntegerField(default=2),
        ),
    ]
