# Generated by Django 4.1.7 on 2023-05-09 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cvdp', '0076_alter_vulnerability_date_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cvdp.action')),
                ('contact', models.ForeignKey(blank=True, help_text='Contact', null=True, on_delete=django.db.models.deletion.CASCADE, to='cvdp.contact')),
                ('group', models.ForeignKey(blank=True, help_text='Group', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            bases=('cvdp.action',),
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='statusrevision',
            options={'get_latest_by': 'revision_number', 'ordering': ('created', 'component_status__component__name')},
        ),
        migrations.CreateModel(
            name='ContactChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Field')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='New Value')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.contactaction')),
            ],
        ),
    ]
