# Generated by Django 4.2.1 on 2023-05-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0078_alter_contactaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentstatus',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
