# Generated by Django 4.2.1 on 2023-05-23 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0079_componentstatus_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.attachment')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.casethread')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
