# Generated by Django 4.2.1 on 2023-05-23 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0080_threadartifact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='message',
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvdp.messagethread'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
