# Generated by Django 4.2.1 on 2023-05-31 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0081_remove_messageattachment_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cvdp.action')),
                ('action_type', models.IntegerField(default=2)),
                ('component', models.ForeignKey(help_text='Component', on_delete=django.db.models.deletion.CASCADE, to='cvdp.component')),
            ],
            bases=('cvdp.action',),
        ),
    ]
