# Generated by Django 4.2.1 on 2023-05-31 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0082_componentaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Field')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='New Value')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.componentaction')),
            ],
        ),
    ]
