# Generated by Django 4.2.1 on 2023-06-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0083_componentchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusrevision',
            name='justification',
            field=models.CharField(blank=True, choices=[('component_not_present', 'Component Not Present'), ('vulnerable_code_not_present', 'Vulnerable Code Not Present'), ('vulnerable_code_not_in_execute_path', 'Vulnerable Code not in Execute Path'), ('vulnerable_code_cannot_be_controlled_by_adversary', 'Vulnerable Code cannot be controlled by adversary'), ('inline_mitigations_already_exist', 'Inline mitigations already exist')], max_length=100, null=True, verbose_name='Justification when status is Not Affected'),
        ),
    ]
