# Generated by Django 4.2.1 on 2023-06-12 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0084_statusrevision_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='copy',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CaseReportOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.case')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.casereport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
