# Generated by Django 4.2.1 on 2023-06-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0085_casereport_copy_casereportoriginal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseparticipant',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('reporter', 'reporter'), ('supplier', 'supplier'), ('participant', 'participant'), ('observer', 'observer')], default='supplier', max_length=30),
        ),
    ]
