# Generated by Django 4.2.1 on 2023-06-14 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0012_apitoken_last_used'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cvdp', '0086_alter_caseparticipant_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdVISEConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='The URL or domain name of the external AdVISE instance', null=True)),
                ('external_key', models.CharField(blank=True, max_length=250, null=True, verbose_name='API Key for external instance')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='The owner of the external AdVISE instance.', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('incoming_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.apitoken')),
            ],
        ),
    ]
