# Generated by Django 4.2.1 on 2023-06-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0087_adviseconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviseconnection',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casereport',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.adviseconnection'),
        ),
    ]
