# Generated by Django 4.2.1 on 2023-07-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0090_casetransfer_data_transferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_text',
            field=models.CharField(blank=True, help_text='Info about author/membership if contact or group are nonexistent/removed', max_length=500, null=True),
        ),
    ]
