# Generated by Django 4.2.1 on 2023-07-25 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0092_alter_post_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentStatusUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vex', models.JSONField(help_text='Status in VEX JSON format')),
                ('received', models.DateTimeField(default=django.utils.timezone.now)),
                ('merged', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
