# Generated by Django 4.2.1 on 2023-07-26 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0093_componentstatusupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentstatusupload',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cvdp.case'),
            preserve_default=False,
        ),
    ]
