# Generated by Django 4.2.1 on 2023-08-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0095_caseresolutionoptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingform',
            name='allow_file_upload',
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'Single Line Text'), (1, 'Multi Line Text'), (2, 'Number'), (3, 'Checkbox Multiple'), (4, 'Checkbox'), (5, 'Select'), (6, 'Email'), (7, 'Date'), (8, 'Radio Buttons'), (9, 'File Input')]),
        ),
    ]
