# Generated by Django 4.2.1 on 2023-10-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0096_remove_reportingform_allow_file_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusrevision',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Affected'), (1, 'Affected'), (2, 'Fixed'), (3, 'Under Investigation'), (4, 'Unknown')]),
        ),
    ]
