# Generated by Django 4.2.1 on 2023-10-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0097_alter_statusrevision_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulssvc',
            name='justifications',
            field=models.JSONField(blank=True, null=True, verbose_name='SSVC Decision Justifications'),
        ),
    ]
