# Generated by Django 4.2.3 on 2023-10-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0099_advisescheduledtask_advisetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisescheduledtask',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
