# Generated by Django 4.2.3 on 2023-11-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0100_advisescheduledtask_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisescheduledtask',
            name='running',
            field=models.BooleanField(default=False, help_text='Needed for longer tasks so multiple workers do not pick it up'),
        ),
        migrations.AddField(
            model_name='advisetask',
            name='running',
            field=models.BooleanField(default=False, help_text='Needed for longer tasks so multiple workers do not pick it up'),
        ),
    ]
