# Generated by Django 4.2.3 on 2023-11-14 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0101_advisescheduledtask_running_advisetask_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Vulnerability'), (2, 'Case'), (3, 'Group'), (4, 'Component')], default=1, verbose_name='Tag Category')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description of tag', max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User that added this tag.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
