# Generated by Django 4.2.3 on 2023-12-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0102_definedtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
    ]
