# Generated by Django 4.2.3 on 2024-01-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0103_alter_action_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseparticipant',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
