# Generated by Django 4.2.3 on 2024-01-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0107_advisoryrevision_version_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusrevision',
            name='default_status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Affected'), (2, 'Unaffected')], default=0),
        ),
    ]
