# Generated by Django 4.2.3 on 2024-01-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0108_statusrevision_default_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusrevision',
            name='version_type',
            field=models.CharField(blank=True, help_text='The version numbering system used for specifying the range. This defines the exact semantics of the comparison (less-than) operation on versions, which is required to understand the range itself.', max_length=50, null=True, verbose_name='Version Type'),
        ),
    ]
