# Generated by Django 4.2.1 on 2023-10-06 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(max_length=50, verbose_name='CVE')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('problem_types', models.JSONField(blank=True, null=True, verbose_name='Problem Type')),
                ('references', models.JSONField(blank=True, null=True, verbose_name='References')),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name='VulnStatus')),
            ],
        ),
        migrations.CreateModel(
            name='SSVCScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_tree', models.JSONField(verbose_name='SSVC Decisions')),
                ('tree_type', models.CharField(max_length=100)),
                ('final_decision', models.CharField(max_length=50)),
                ('vector', models.CharField(max_length=100)),
                ('last_edit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adscore.vul')),
            ],
        ),
    ]
