# Generated by Django 4.2.1 on 2023-10-11 18:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adscore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vul',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='vul',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='vul_cve_gin'),
        ),
    ]
