# Generated by Django 4.2.1 on 2023-10-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adscore', '0002_vul_search_vector_vul_vul_cve_gin'),
    ]

    operations = [

        migrations.RunSQL(
            sql='''

            CREATE TRIGGER adscore_update_trigger
            BEFORE INSERT OR UPDATE of description, cve
            ON adscore_vul
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'pg_catalog.english', description, cve);

            UPDATE adscore_vul SET search_vector = NULL;
            ''',

            reverse_sql= '''
            DROP TRIGGER IF EXISTS adscore_update_trigger
            ON adscore_vul;
            ''',
        ),



    ]
