# Generated by Django 4.2.1 on 2023-10-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adscore', '0003_auto_20231011_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vul',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
