# Generated by Django 4.2.1 on 2023-10-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adscore', '0005_ssvcscore_justifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='vul',
            name='locked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Record is locked for scoring'),
        ),
    ]
