# Generated by Django 4.2.1 on 2023-10-16 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adscore', '0006_vul_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vul',
            name='locked',
        ),
        migrations.CreateModel(
            name='VulLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.DateTimeField(auto_now=True, verbose_name='Record is locked for scoring')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Scoring')),
                ('vul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adscore.vul')),
            ],
        ),
    ]
