# Generated by Django 4.2.3 on 2023-10-24 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adscore', '0007_remove_vul_locked_vullock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSVCScoreActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('edit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified Date')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adscore.ssvcscore')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Field')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='New Value')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adscore.ssvcscoreactivity')),
            ],
        ),
    ]
